//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public calisanlar()
        {
            this.iadeler = new HashSet<iadeler>();
            this.satislar = new HashSet<satislar>();
        }
    
        public int Calisan_id { get; set; }
        public string Calisan_tc { get; set; }
        public string Calisan_adi { get; set; }
        public string Calisan_soyadi { get; set; }
        public string Kullanici_adi { get; set; }
        public string Parola { get; set; }
        public int Rol_id { get; set; }
    
        public virtual roller roller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iadeler> iadeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satislar> satislar { get; set; }
    }
}
