//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketOtomasyonDBEntities : DbContext
    {
        public MarketOtomasyonDBEntities()
            : base("name=MarketOtomasyonDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calisanlar> calisanlar { get; set; }
        public virtual DbSet<iadeler> iadeler { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<roller> roller { get; set; }
        public virtual DbSet<satislar> satislar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<son24saatsatis> son24saatsatis { get; set; }
        public virtual DbSet<StokBitenUrunler> StokBitenUrunler { get; set; }
        public virtual DbSet<TarihiGecmisUrunler> TarihiGecmisUrunler { get; set; }
    }
}
