//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        public int satis_id { get; set; }
        public int calisan_id { get; set; }
        public int urun_id { get; set; }
        public double satis_fiyat { get; set; }
        public System.DateTime satis_tarihi { get; set; }
        public int adet { get; set; }
    
        public virtual calisanlar calisanlar { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
