//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokBitenUrunler
    {
        public int Urun_id { get; set; }
        public string Urun_adi { get; set; }
        public int stok { get; set; }
        public string Kategori_adi { get; set; }
        public double fiyat { get; set; }
        public double alis_fiyat { get; set; }
        public System.DateTime uretim_tarihi { get; set; }
        public System.DateTime tuketim_tarihi { get; set; }
    }
}
